name: Build and Deploy to AWS ECR

on:
  push:
    branches: [main, develop]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      ECR_REPO_BACKEND: ${{ secrets.ECR_REPO_BACKEND }}
      ECR_REPO_FRONTEND: ${{ secrets.ECR_REPO_FRONTEND }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and Push Backend Docker Image
        run: |
          docker build -t $ECR_REPO_BACKEND:latest -f backend/Dockerfile ./backend
          docker tag $ECR_REPO_BACKEND:latest $ECR_REPO_BACKEND:latest
          docker push $ECR_REPO_BACKEND:latest

      - name: Build and Push Frontend Docker Image
        run: |
          docker build -t $ECR_REPO_FRONTEND:latest -f frontend/Dockerfile ./frontend
          docker tag $ECR_REPO_FRONTEND:latest $ECR_REPO_FRONTEND:latest
          docker push $ECR_REPO_FRONTEND:latest

